
version: "3"

services:
  websocket_server:
    build:
      context: ./websocket_server
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - websocket_server

