
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8001:8000"
    networks:
      - mynetwork
    restart: always
    # env_file: .env

  # websocket_server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.websocket
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - mynetwork
  #   restart: always


networks:
  mynetwork:
    driver: bridge

