version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IP: ${IP}
        WEBSOCK_PORT: ${WEBSOCK_PORT}
    ports:
      - "${NGINX_PORT}:80"
      - "8001:${WEBSOCK_PORT}"
    networks:
      - mynetwork
    restart: always
    env_file: .env

networks:
  mynetwork:
    driver: bridge

