
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8001:8000"
    networks:
      - mynetwork

  websocket_server:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

