
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  websocket_server:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8000:8000"

